{
  # Tokens
  "data_path": "/data/pretraining-mix/pretraining-mix_text_document",
  "vocab_file": "/data/neox_tokenizer/tokenizer.json",
  "tokenizer_type": "HFTokenizer",
  "data_impl": "mmap",

  # Logging
  "checkpoint_validation_with_forward_pass": False,
  "tensorboard_dir": "tensorboard",
  "log_dir": "logs",
  "log_interval": 10,
  "steps_per_print": 10,
  "wall_clock_breakdown": true,
  "use_wandb": True,
  "wandb_host": "https://api.wandb.ai",
  "wandb_project": "AISI",
  "wandb_team": "eleutherai",
  "wandb_run_name": "pretraining_baseline",

  # Distributed Training
  "hostfile": "/workspace/hostfile",
  "deepspeed_mpi": True,
  "launcher": "openmpi",
  "deepspeed_extra_args": { "ssh_port": 2222 },
  "pipe_parallel_size": 1,
  "model_parallel_size": 1,

  # Training Duration
  # 500B (tokens) / (4 (grad acc) * 32 (world size) * 16 (micro batch size) * 2048 (seq length))
  "train_iters": 119209,
  "lr_decay_iters": 119209,
  "distributed_backend": "nccl",
  "lr_decay_style": "cosine",
  "warmup": 0.01,
  "split": "100,0,0",

  # Architecture
  "num_layers": 32,
  "hidden_size": 4096,
  "num_attention_heads": 32,
  "seq_length": 2048,
  "max_position_embeddings": 2048,
  "norm": "layernorm",
  "pos_emb": "rotary",
  "rotary_pct": 0.25,
  "no_weight_tying": true,
  "gpt_j_residual": true,
  "output_layer_parallelism": "column",
  "attention_config": [[["flash"], 32]],
  "scaled_upper_triang_masked_softmax_fusion": true,
  "precision": "bfloat16",
  "activation": "gelu",
  # "activation": "swiglu", TODO: Support SwiGLU

  # Transformer Engine
  "te_columnparallel": false,
  "te_rowparallel": false,
  "te_layernorm_mlp": true,
  "te_mha": true,
  "te_fp8_format": "hybrid",
  "te_fp8_wgrad": false,
  "te_fp8_amax_history_len": 1,
  "te_fp8_amax_compute_algo": "most_recent",
  "te_fp8_margin": 0,
  "te_fp8_mha": false,

  # Optimization
  # 0.0003 is OLMo 2's peak learning rate
  "optimizer":
    {
      "type": "Adam",
      "params": { "lr": 0.0003, "betas": [0.9, 0.95], "eps": 1.0e-8 },
    },
  "min_lr": 0.000012,
  "zero_optimization":
    {
      "stage": 1,
      "allgather_partitions": true,
      "allgather_bucket_size": 1260000000,
      "overlap_comm": true,
      "reduce_scatter": true,
      "reduce_bucket_size": 1260000000,
      "contiguous_gradients": true,
      "cpu_offload": false,
    },
  "train_micro_batch_size_per_gpu": 16,
  "gradient_accumulation_steps": 4,
  "gradient_clipping": 1.0,
  "weight_decay": 0.1,
  "hidden_dropout": 0,
  "attention_dropout": 0,

  # Checkpointing
  "checkpoint_activations": true,
  "checkpoint_num_layers": 1,
  "partition_activations": true,
  "synchronize_each_layer": true,
  "checkpoint_factor": 2000,
  "save": "/checkpoints/pretraining_baseline",
  "load": "/checkpoints/pretraining_baseline",

  # Evaluation
  "eval_iters": 0,
  "eval_interval": 5,
  "eval_results_prefix": "pretraining_baseline",
  # TODO: Add automatic evals for next runs
  #"eval_tasks": ["wmdp_bio"],
  # "do_valid",
  # "eval_tasks": ["wmdp", "mmlu", "piqa", "arc-easy", "arc-challenge", "lambada", "hellaswag"]
}
