# Parameters used for text generation
# Make sure `load` is specified somewhere else
{
  # Text gen type: `input-file`, `unconditional` or `interactive`
  "text_gen_type": "unconditional",

  # Params for all
  "maximum_tokens": 102,
  "minimum_tokens": 0,
  "prompt_end": "\n",
  "temperature": 1.0,
  "top_p": 0.0,
  "min_p": 0.0,
  "top_h": 0.0,
  "typical_p": 1.0,
  "epsilon_cutoff": 0.0,
  "eta_cutoff": 0.0,
  "top_k": 0,
  "recompute": false,

  # `unconditional`: samples
  "num_samples": 10,

  # input/output file
  "sample_input_file": "sample_input.txt",
  "sample_output_file": "sample_output.txt",
}
