{
  "seed": 4,
  "data_path": "/data/pile/datasets--EleutherAI--pile-preshuffled-seeds/snapshots/27a5768e205eab4c2ddec1f3d2ab8cd56ba85519/seed4/pile_20B_tokenizer_text_document",
  "save": "/checkpoints/2-8b-seed-4",
  "load": "/checkpoints/2-8b-seed-4"
}